services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_bookdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask-book-app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql://root:password@db:3306/flask_bookdb
      SECRET_KEY: dev_key
    volumes:
      - .:/app

volumes:
  db_data:




